kepo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from kepo_app.views import IndexView, InfoPtnView, EditArticleView, AddArticleView, AdminLoginView, ArticleView, MerchView, AboutView, LogoutView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('info_ptn/', InfoPtnView.as_view(), name="info_ptn"),
    path('article/<slug:article_slug>/edit/', EditArticleView.as_view(), name="edit_article"),
    path('article/<slug:article_slug>/delete/', EditArticleView.as_view(), name="delete_article"),
    path('add_article/', AddArticleView.as_view(), name="add_article"),
    path('admin_login/', AdminLoginView.as_view(), name="admin_login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('about/', AboutView.as_view(), name="about"),
    path('article/<slug:article_slug>', ArticleView.as_view(), name="article"),
    path('merch/', MerchView.as_view(), name="merch"),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kepo_app/forms.py
from django import forms
from kepo_app.models import Category, Article
from django.core.exceptions import ValidationError

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=Category._meta.get_field("name").max_length, help_text="Enter the category name!",)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Category
        fields = ('name',)

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=Article._meta.get_field("title").max_length, help_text="Title",
    )
    content = forms.CharField(widget=forms.Textarea, help_text="Content",)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Article
        exclude = ('category',)

templates/about.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/styleAbout.css' %}" />
{% endblock style %}

{% block content %}
    <section class="section-top">
      <div class="title">
        <h1>About Us</h1>
      </div>

      <div class="slide-about">
        <!-- Full-width images with number and caption text -->
        <div class="carousel fade">
          <div class="text">
            <h2>Our Event</h2>
            <p>
              Kedubes Expo 2022 atau biasa disingkat KEPO adalah acara tahunan yang menjadi sarana pemberian informasi kepada siswa/i SMAN 12 Jakarta terkait berbagai program studi di perguruan tinggi. Kedubes Expo 2022 bertujuan memudahkan
              dalam menentukan pilihan masa depan untuk ke jenjang berikutnya diselenggarakan oleh Alumni SMAN 12 Jakarta.
            </p>
            <br/>
            <br/>
            <br/>
          </div>
        </div>

        <div class="carousel fade">
          <div class="text">
            <h2>Our Goals</h2>
            <ul>
              <li>Memberikan pengetahuan mengenai fakultas/jurusan/program studi di perguruan tinggi kepada siswa siswi SMAN 12 Jakarta;</li>
              <li>Memperkenalkan atau sebagai introduksi tentang kehidupan perkuliahan kepada siswa siswi SMAN 12 Jakarta;</li>
              <li>Memberi pengetahuan tentang tahapan dan motivasi mengenai berbagai jalur masuk perguruan tinggi;</li>
              <li>Memberi pengetahuan tentang kompetensi (soft skill dan hard skill) yang perlu dimiliki mahasiswa di perguruan tinggi;</li>
              <li>Membantu siswa siswi SMAN 12 Jakarta dalam menentukan jurusan.</li>
            </ul>
          </div>
        </div>

        <div class="carousel fade">
          <div class="text">
            <h2>Our Theme</h2>
            <p>
              Kedubes Expo tahun ini mengangkat tema "Let your magic carpet bring you to the whole new world" yang terinspirasi dari film disney “Aladdin”. Tema tersebut menggambarkan bahwa KEPO 2022 merupakan sebuah sarana yang akan
              memberikan gambaran kepada siswa/i SMAN 12 Jakarta mengenai kehidupan baru yang akan mereka lalui di jenjang selanjutnya yaitu dunia perkuliahan
            </p>
            <br/>
            <br/>
            <br/>
          </div>
        </div>
        <!-- Next and previous buttons -->
        <a class="prev" onclick="nextSlides(-1)">&#10094;</a>
        <a class="next" onclick="nextSlides(1)">&#10095;</a>
      </div>
      <br />

      <!-- The dots/circles -->
      <div style="text-align: center">
        <span class="dot" onclick="activeSlide(1)"></span>
        <span class="dot" onclick="activeSlide(2)"></span>
        <span class="dot" onclick="activeSlide(3)"></span>
      </div>
    </section>

    <section>
      <div class="title">
        <h1>Meet The Team</h1>
      </div>
      <div class="slide-container">
        <div class="mySlide">
          <img class="mySlides1 fade" src="{% static 'images/projectleader-1.png' %}" alt="" />
          <img class="mySlides1 fade" src="{% static 'images/projectleader-2.png' %}" alt="" />
          <img class="mySlides1 fade" src="{% static 'images/projectleader-3.png' %}" alt="" />
          <img class="mySlides1 fade" src="{% static 'images/projectleader-4.png' %}" alt="" />
          <!-- Next and previous buttons -->
          <a class="prev" onclick="plusDivs(-1,0)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,0)">&#10095;</a>
        </div>
        <div class="mySlide">
          <img class="mySlides2 fade" src="{% static 'images/event-1.png' %}" alt="" />
          <img class="mySlides2 fade" src="{% static 'images/event-2.png' %}" alt="" />
          <img class="mySlides2 fade" src="{% static 'images/event-3.png' %}" alt="" />
          <img class="mySlides2 fade" src="{% static 'images/event-4.png' %}" alt="" />
          <a class="prev" onclick="plusDivs(-1,1)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,1)">&#10095;</a>
        </div>
        <div class="mySlide">
          <img class="mySlides3 fade" src="{% static 'images/fundraising-1.png' %}" alt="" />
          <img class="mySlides3 fade" src="{% static 'images/fundraising-2.png' %}" alt="" />
          <a class="prev" onclick="plusDivs(-1,2)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,2)">&#10095;</a>
        </div>
        <div class="mySlide">
          <img class="mySlides4 fade" src="{% static 'images/operational-1.png' %}" alt="" />
          <img class="mySlides4 fade" src="{% static 'images/operational-2.png' %}" alt="" />
          <img class="mySlides4 fade" src="{% static 'images/operational-3.png' %}" alt="" />
          <a class="prev" onclick="plusDivs(-1,3)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,3)">&#10095;</a>
        </div>
        <div class="mySlide">
          <img class="mySlides5 fade" src="{% static 'images/creative-1.png' %}" alt="" />
          <img class="mySlides5 fade" src="{% static 'images/creative-2.png' %}" alt="" />
          <img class="mySlides5 fade" src="{% static 'images/creative-3.png' %}" alt="" />
          <a class="prev" onclick="plusDivs(-1,4)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,4)">&#10095;</a>
        </div>
        <div class="mySlide">
          <img class="mySlides6 fade" src="{% static 'images/communication-1.png' %}" alt="" />
          <img class="mySlides6 fade" src="{% static 'images/communication-2.png' %}" alt="" />
          <img class="mySlides6 fade" src="{% static 'images/communication-3.png' %}" alt="" />
          <img class="mySlides6 fade" src="{% static 'images/communication-4.png' %}" alt="" />
          <a class="prev" onclick="plusDivs(-1,5)">&#10094;</a>
          <a class="next" onclick="plusDivs(1,5)">&#10095;</a>
        </div>
      </div>
    </section>
<script src="{% static 'js/about_slider.js' %}"></script>
<script src="{% static 'js/team_slider.js' %}"></script>
{% endblock content %}

templates/admin_login.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  <link rel="stylesheet" href='{% static "css/styleIndex.css" %}'>
  <link rel="stylesheet" href='{% static "css/styleAdminLogin.css" %}'>
{% endblock style %}

{% block content %}
    <section class="landing-content section1">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    ADMIN PANEL
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name="username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" i>
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
                <div><a href="/logout" type="button" class="btn-outline-danger">Logout</a></div>
            </div>
        </div>
    </section>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/countdown.js' %}"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>AOS.init();</script>
{% endblock content %}

templates/edit_article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/styleInfo.css' %}" />
    <script src="https://cdn.tiny.cloud/1/c4q70qjgydgdgqd2twn1f6nu8bvkcot4dk5xeaaomq93rky4/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <title>Info Perguruan Tinggi</title>
    <script>
        tinymce.init({
            selector: '#id_content',
            plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
            imagetools_cors_hosts: ['picsum.photos'],
            menubar: '',
            toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl',
            toolbar_sticky: true,
            autosave_ask_before_unload: true,
            autosave_interval: '30s',
            autosave_prefix: '{path}{query}-{id}-',
            autosave_restore_when_empty: false,
            autosave_retention: '2m',
            image_advtab: true,
            link_list: [
                { title: 'My page 1', value: 'https://www.tiny.cloud' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_list: [
                { title: 'My page 1', value: 'https://www.tiny.cloud' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_class_list: [
                { title: 'None', value: '' },
                { title: 'Some class', value: 'class-name' }
            ],
            importcss_append: true,
            file_picker_callback: function (callback, value, meta) {
                /* Provide file and text for the link dialog */
                if (meta.filetype === 'file') {
                callback('https://www.google.com/logos/google.jpg', { text: 'My text' });
                }

                /* Provide image and alt text for the image dialog */
                if (meta.filetype === 'image') {
                callback('https://www.google.com/logos/google.jpg', { alt: 'My alt text' });
                }

                /* Provide alternative source and posted for the media dialog */
                if (meta.filetype === 'media') {
                callback('movie.mp4', { source2: 'alt.ogg', poster: 'https://www.google.com/logos/google.jpg' });
                }
            },
            templates: [
                    { title: 'New Table', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
                { title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...' },
                { title: 'New list with dates', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
            ],
            template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
            template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
            height: 600,
            image_caption: true,
            quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
            noneditable_noneditable_class: 'mceNonEditable',
            toolbar_mode: 'sliding',
            contextmenu: 'link image imagetools table',
            // skin: useDarkMode ? 'oxide-dark' : 'oxide',
            // content_css: useDarkMode ? 'dark' : 'default',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
        });
    </script>
  </head>
  <body>
    <nav>
      <div class="nav-logo">
        <img src="{% static 'images/logo.png' %}" alt="Kepo 2022" />
        <h4>
          <a href="index.html"> Kedubes<br />Expo</a>
        </h4>
      </div>
      <ul>
        <li>
          <a href="/info_ptn">Info</a>
        </li>

        <li>
          <a href="/merch">Merch</a>
        </li>

        <li>
          <a href="/about.html">About Us</a>
        </li>
      </ul>
    </nav>

    <section class="section1">
        <!-- <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_select_category">Select Category:</label>
                <select name="cat">
                    {% for category in category_list %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form> -->
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {{ form.non_field_errors }}
            <div>
                <label for="id_select_category">Select Category:</label>
                <select name="cat">
                    {% for category in category_list %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="id_title">Title:</label>
                <input type="text" name="title" size="240" id="id_title" value="{{ article.title }}">
            </div>
            <div>
                <label for="id_thumbnail">Thumbnail:</label>
                <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail">
            </div>
            <div>
                <label for="id_content">Content:</label>
                <textarea id="id_content" name="content" rows="30" cols="50">{{article.content | safe}}</textarea>
            </div>
            <!-- {%for field in form%}
                    <div class="form-group">
                        <label class="mylabel">{{ field.label }}</label>
                        {{field}}
                    </div>
                {%endfor%} -->
            <button type="submit">Edit</button>
        </form>
    </section>
    
    <footer>
      <div class="footer-logo">
        <img src="{% static 'images/logo_footer.png' %}" alt="logo" />
      </div>
      <div class="footer-content">
        <p>Find us on social media</p>
        <a href="https://www.instagram.com/kepokedubes/" target="_blank"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-linkedin-square"></i></a>
        <p>©2021 Kedubes Expo 2022</p>
      </div>
    </footer>
  </body>
</html>

templates/infoptn_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/styleInfo.css' %}" />
    <script src="https://cdn.tiny.cloud/1/c4q70qjgydgdgqd2twn1f6nu8bvkcot4dk5xeaaomq93rky4/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <title>Info Perguruan Tinggi</title>
    <script>
        tinymce.init({
            selector: '#id_content',
            plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
            imagetools_cors_hosts: ['picsum.photos'],
            menubar: '',
            toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl',
            toolbar_sticky: true,
            autosave_ask_before_unload: true,
            autosave_interval: '30s',
            autosave_prefix: '{path}{query}-{id}-',
            autosave_restore_when_empty: false,
            autosave_retention: '2m',
            image_advtab: true,
            link_list: [
                { title: 'My page 1', value: 'https://www.tiny.cloud' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_list: [
                { title: 'My page 1', value: 'https://www.tiny.cloud' },
                { title: 'My page 2', value: 'http://www.moxiecode.com' }
            ],
            image_class_list: [
                { title: 'None', value: '' },
                { title: 'Some class', value: 'class-name' }
            ],
            importcss_append: true,
            file_picker_callback: function (callback, value, meta) {
                /* Provide file and text for the link dialog */
                if (meta.filetype === 'file') {
                callback('https://www.google.com/logos/google.jpg', { text: 'My text' });
                }

                /* Provide image and alt text for the image dialog */
                if (meta.filetype === 'image') {
                callback('https://www.google.com/logos/google.jpg', { alt: 'My alt text' });
                }

                /* Provide alternative source and posted for the media dialog */
                if (meta.filetype === 'media') {
                callback('movie.mp4', { source2: 'alt.ogg', poster: 'https://www.google.com/logos/google.jpg' });
                }
            },
            templates: [
                    { title: 'New Table', description: 'creates a new table', content: '<div class="mceTmpl"><table width="98%%"  border="0" cellspacing="0" cellpadding="0"><tr><th scope="col"> </th><th scope="col"> </th></tr><tr><td> </td><td> </td></tr></table></div>' },
                { title: 'Starting my story', description: 'A cure for writers block', content: 'Once upon a time...' },
                { title: 'New list with dates', description: 'New List with dates', content: '<div class="mceTmpl"><span class="cdate">cdate</span><br /><span class="mdate">mdate</span><h2>My List</h2><ul><li></li><li></li></ul></div>' }
            ],
            template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
            template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
            height: 600,
            image_caption: true,
            quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
            noneditable_noneditable_class: 'mceNonEditable',
            toolbar_mode: 'sliding',
            contextmenu: 'link image imagetools table',
            // skin: useDarkMode ? 'oxide-dark' : 'oxide',
            // content_css: useDarkMode ? 'dark' : 'default',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
        });
    </script>
  </head>
  <body>
    <nav>
      <div class="nav-logo">
        <img src="{% static 'images/logo.png' %}" alt="Kepo 2022" />
        <h4>
          <a href="index.html"> Kedubes<br />Expo</a>
        </h4>
      </div>
      <ul>
        <li>
          <a href="/info_ptn">Info</a>
        </li>

        <li>
          <a href="/merch">Merch</a>
        </li>

        <li>
          <a href="/about.html">About Us</a>
        </li>
      </ul>
    </nav>

    <section class="section1">
        <!-- <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <label for="id_select_category">Select Category:</label>
                <select name="cat">
                    {% for category in category_list %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form> -->
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {{ form.non_field_errors }}
            
            <div>
                <label for="id_select_category">Select Category:</label>
                <select name="cat">
                    {% for category in category_list %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <label for="id_title">Title:</label>
                <input type="text" name="title" size="240" id="id_title">
            </div>
            <div>
                <label for="id_thumbnail">Thumbnail:</label>
                <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail">
            </div>
            <div>
                <label for="id_content">Content:</label>
                <textarea id="id_content" name="content" rows="30" cols="50"></textarea>
            </div>
            <!-- {%for field in form%}
                    <div class="form-group">
                        <label class="mylabel">{{ field.label }}</label>
                        {{field}}
                    </div>
                {%endfor%} -->
            <button type="submit">Upload</button>
        </form>
    </section>
    
    <footer>
      <div class="footer-logo">
        <img src="{% static 'images/logo_footer.png' %}" alt="logo" />
      </div>
      <div class="footer-content">
        <p>Find us on social media</p>
        <a href="https://www.instagram.com/kepokedubes/" target="_blank"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-linkedin-square"></i></a>
        <p>©2021 Kedubes Expo 2022</p>
      </div>
    </footer>
  </body>
</html>

templates/merch.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
<link rel="stylesheet" href='{% static "css/styleIndex.css" %}'>
<link rel="stylesheet" href='{% static "css/styleMerch.css" %}'>
{% endblock style %}

{% block content %}

    <section class="landing-content merch">
      <div id="title">
        <h5>Open PO</h5>
        <div style="display: flex;">
          <img id="star-left" src="{% static 'images/star.png' %}" />
          <h1 style="margin: 0 1rem;">Official Merchandise</h1>
          <img id="star-right" src="{% static 'images/star.png' %}" />
        </div>
      </div>
      
      <div id="posters">
        <img src="{% static 'images/rug_merch_left.png' %}" alt="Rug Left" id="rug-left">
        <img src="{% static 'images/Preorder-2-Bundle-Package-New.png' %}" alt="Poster 1" class="merch-poster">
        <img src="{% static 'images/Preorder-2-non-bundle-New.png' %}" alt="Poster 2" class="merch-poster">
        <img src="{% static 'images/rug_merch_right.png' %}" alt="Rug Left" id="rug-right">
      </div>
      <div>
        <a href="https://bit.ly/OrderMerchKEPO2022"><button id="order-btn">Order Now!</button></a>
      </div>
    
  

    <footer>
      <div class="footer-logo">
        <img src="{% static 'images/logo_footer.png' %}" alt="logo" />
      </div>
      <div class="footer-content">
        <p>Find us on social media</p>
        <a href="https://www.instagram.com/kepokedubes/" target="_blank"><i class="fa fa-instagram"></i></a>
        <p>©2021 Kedubes Expo 2022</p>
      </div>
    </footer>
  </section>
{% endblock content %}
{% block footer %}{% endblock footer %}